import useSpotreba from '../hooks/useSpotreba'
import { formatExp, fmtEur } from '../../../utils/predajUtils'

export default function Spotreba() {
  const s=useSpotreba()
  return <div className='max-w-md mx-auto p-4 pb-24'>
    <h1 className='text-2xl font-bold mb-3'>Spotreba</h1>
    {s.msg && <div className='border rounded-xl p-3 mb-3'>{s.msg}</div>}
    <div className='space-y-3'>
      <select className='w-full border rounded-xl px-3 py-3 text-lg' value={s.komuId} onChange={e=>s.setKomuId(e.target.value)}><option value=''>— Komu bolo vydané —</option>{s.users.map(u=><option key={u.id} value={u.id}>{u.nazov}</option>)}</select>
      <div className='border rounded-xl p-3'><div className='flex flex-wrap gap-1'>{s.letters.map(l=><button key={l} className={`px-2 py-1 rounded border ${s.letter===l?'bg-black text-white':''}`} onClick={()=>{s.setLetter(l);s.setProduktId('')}}>{l}</button>)}</div><input className='w-full border rounded-xl px-3 py-2 mt-2' placeholder='Hľadať produkt…' value={s.query} onChange={e=>s.setQuery(e.target.value)}/></div>
      <select className='w-full border rounded-xl px-3 py-3 text-lg' value={s.produktId} onChange={e=>s.setProduktId(e.target.value)}><option value=''>— Vyber produkt —</option>{s.filteredProducts.map(p=><option key={p.id} value={p.id}>{p.nazov}</option>)}</select>
      <select className='w-full border rounded-xl px-3 py-3 text-lg' value={s.selectedBatchId} onChange={e=>s.setSelectedBatchId(e.target.value)} disabled={!s.produktId}><option value=''>— Ručne vyber šaržu / EXP —</option>{s.batchOptions.map(r=><option key={r.id} value={r.id}>{r.sklady?.nazov ?? `Sklad ${r.sklad_id}`} · EXP {r.expiracia?formatExp(r.expiracia):'—'} · {Number(r.mnozstvo)||0} ks</option>)}</select>
      {s.selectedBatch && <div className='border rounded-xl p-3 text-sm'>Dostupné: <b>{Number(s.selectedBatch.mnozstvo)||0} ks</b> · Nákupná cena: <b>{fmtEur(s.selectedBatch.nakupna_cena)}</b></div>}
      <div className='flex gap-2'><input inputMode='numeric' className='flex-1 border rounded-xl px-3 py-3' placeholder='Množstvo' value={s.qty} onChange={e=>s.setQty(e.target.value.replace(/[^\d]/g,''))}/><button className='border rounded-xl px-4' onClick={s.addToCart}>Pridať</button></div>
      <select className='w-full border rounded-xl px-3 py-3' value={s.dovod} onChange={e=>s.setDovod(e.target.value)}><option value=''>— Dôvod voliteľný —</option>{['Interná spotreba','Tester','Poškodené','Expirované','Dar','Reklamácia','Iné'].map(x=><option key={x}>{x}</option>)}</select>
      <textarea className='w-full border rounded-xl px-3 py-3' rows='3' placeholder='Poznámka (voliteľné)' value={s.poznamka} onChange={e=>s.setPoznamka(e.target.value)}/>
    </div>
    <div className='border rounded-xl p-3 mt-3'><div className='flex justify-between font-semibold'><span>Košík spotreby</span><span>{fmtEur(s.totalBuy)}</span></div>{s.cart.length===0?<div className='text-sm opacity-70 mt-2'>Zatiaľ prázdne.</div>:s.cart.map((i,idx)=><div key={`${i.zasoba_id}-${idx}`} className='border rounded-xl p-3 mt-2'><div className='font-bold'>{i.produkt_nazov}</div><div className='text-sm'>{i.sklad_nazov} · EXP {i.expiracia?formatExp(i.expiracia):'—'} · {i.qty} ks · {fmtEur(i.nakupna_cena)}</div><button className='text-sm underline mt-2' onClick={()=>s.removeItem(idx)}>Odstrániť</button></div>)}<input className='w-full border rounded-xl px-3 py-2 mt-3' placeholder='Názov rozpracovanej spotreby' value={s.draftName} onChange={e=>s.setDraftName(e.target.value)}/><div className='grid grid-cols-2 gap-2 mt-2'><button className='border rounded-xl py-3 font-semibold' disabled={s.loading||!s.cart.length} onClick={s.saveDraft}>💾 Uložiť</button><button className='border rounded-xl py-3 font-semibold' disabled={s.loading||!s.cart.length} onClick={s.finish}>{s.loading?'Ukladám…':'Dokončiť'}</button></div></div>
    <div className='border rounded-xl p-3 mt-3'><div className='flex justify-between'><b>Rozpracované spotreby</b><button className='underline text-sm' onClick={()=>s.setDraftOpen(v=>!v)}>{s.draftOpen?'Skryť':`Zobraziť (${s.drafts.length})`}</button></div>{s.draftOpen&&<div className='space-y-2 mt-2'>{s.drafts.map(d=><div key={d.id} className='border rounded-xl p-3'><b>{d.nazov||'Bez názvu'}</b><div className='text-sm opacity-70'>{d.komu_nazov} · {d.itemsCount} položiek</div><div className='flex gap-3 mt-2'><button className='underline text-sm' onClick={()=>s.loadDraft(d)}>Načítať</button><button className='underline text-sm' onClick={()=>s.deleteDraft(d.id)}>Vymazať</button></div></div>)}</div>}</div>
    <div className='border rounded-xl p-3 mt-3'><b>Posledné spotreby</b>{s.recent.map(r=><div key={r.id} className='border rounded-xl p-3 mt-2'><b>{r.komu_nazov}</b><div className='text-sm opacity-70'>{new Date(r.created_at).toLocaleString('sk-SK')} · {r.totalQty} ks · {fmtEur(r.totalBuy)}</div></div>)}</div>
  </div>
}
